{
 "title": "Simulator Requests per Second",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Requests Per Second by Status",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(simulator_requests_total[1m])) by (status)"
    }
   ]
  },
  {
   "title": "Request Per Second",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(simulator_requests_total{status=\"200\"}[1m])) by (status)"
    }
   ]
  },
  {
   "title": "Request per Second by service and status",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(simulator_requests_total[1m])) by (status, service)"
    }
   ]
  }
 ]
}